# pubspec.yaml
name: detectorfilagasolina
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  camera: ^0.11.1
  tflite_flutter: ^0.11.0 # Asegúrate de que esta sea la última versión estable si hay una más nueva.
  image: ^4.1.7
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/tflite/ssd_mobilenet.tflite
    - assets/tflite/labelmap.txt 
    - assets/tflite/lpr/labelmap.txt   # Labelmap para ssd_mobilenet (general)
    - assets/tflite/lpr/detect.tflite
     # <--- AHORA REFERENCIA labelmap.txt
    # Si tienes el modelo OCR y sus etiquetas, descomenta estas líneas:
    # - assets/tflite/lpr/license_plate_ocr.tflite
    # - assets/tflite/lpr/labelmap_ocr.txt
    - assets/images/bus.png
    - assets/images/car.png
    - assets/images/motorcycle.png
    - assets/images/truck.png